version: "3"
services:
    client:
        build: ./client
        image: catpic.azurecr.io/client
        ports:
            - "80:80"
        depends_on:
            - api
    api:
        build: ./api
        image: catpic.azurecr.io/api
        ports:
            - "5000:5000"
