version: "3"
services:
    client:
        build: ./client
        ports:
            - "80:3000"
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
